Jdp230901-11  Task Order Entity
piotr-grosicki/project-jdp-2309-01 pull request #14
Opened 2023-08-28 09:15 UTC by CzaHa02

2023-08-28 16:54 UTC, Patryk241194 requested changes
Hej @CzaHa02,

Mam dwie uwagi - w komentarzach poniżej.

PS. Fajnie by było jakbyś jeszcze przy okazji tworzenia encji Order odkomentował relację między **Order-User** w encji User, którą musiałem zakomentować, aby budował się projekt.

2023-08-28 16:54 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +  Po zrobieniu Product Entity
Moim zdaniem powinniśmy tu zastosować relacje **@ManyToMany** zgodnie ze schematem jaki przyjęliśmy.
Wiele zamówień może zawierać te same produkty, co oznacza, że produkty są współdzielone między różnymi zamówieniami.

2023-08-28 16:54 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Optional<Order> findById(@NotNull Long id);
Moim zdaniem adnotacja **@NotNull** jest tu niepotrzebna. Zdaje się, że adnotacja @NotNull ma sens głównie w kontekście encji lub DTO, aby oznaczyć konkretne pola jako wymagające wartości not-null, nie ma wpływu na zachowanie operacji dla repozytorium.

2023-08-28 21:24 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +  Po zrobieniu Product Entity
Podpisuję się pod tym ręcami i nogami

2023-08-28 21:26 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Optional<Order> findById(@NotNull Long id);
Tak jak Patryk pisze, zwłaszcza że chętnie bym proponował pójście w zamieszczanie @NotNull przy klasach DTO i @Valid przy argumentach żądań controllerów, aby stworzyć odpowiedni wzorzec zachowania aplikacji w odpowiedzi na błędne dane wysyłane przez użytkowników naszego api

2023-08-28 21:26 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Optional<Order> findById(@NotNull Long id);
Wówczas po prostu do tego tutaj miejsca, które komentujemy, nie dojdzie nigdy null

2023-08-29 10:58 UTC, CzaHa02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +  Po zrobieniu Product Entity
masz racje zgadzam sie i poprawiam

2023-08-29 11:30 UTC, closed without merging

2023-08-29 12:12 UTC, enmebaraggesi reviewed
:raised_hands: