Entity fixes and properties change for MySql
piotr-grosicki/project-jdp-2309-01 pull request #18
Opened 2023-08-29 19:17 UTC by Patryk241194

Cześć,

Wykonałem drobne korekty encji po wszystkich mergach wynikające z faktu, że kilka drobiazgów powodowało, że bazy niepoprawnie się budowały. Zerknijcie na to i dajcie znać czy jest ok, u mnie wszystko przechodzi i baza danych buduje się poprawnie.

Dodatkowo zmiany w application.properties - teraz są poprawnie ustawione pod MySql.

2023-08-29 20:39 UTC, wojmys approved these changes

2023-08-29 21:13 UTC, TomaszGajewski09 approved these changes

2023-08-30 10:08 UTC, CzaHa02 approved these changes

2023-08-30 14:24 UTC, enmebaraggesi requested changes
Nadal istnieje problem z płaczącym circleci :tired_face:

2023-08-30 19:15 UTC, closed without merging