#1 modified CartController
piotr-grosicki/project-jdp-2309-01 pull request #2
Opened 2023-08-19 16:09 UTC by enmebaraggesi

Had to add mysql connector dependency because of com.mysql.jdbc.Driver issue.

2023-08-21 06:10 UTC, piotr-grosicki requested changes

2023-08-21 06:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<String> createNewCartWithUserId(@RequestParam Long user_id) {
uzywamy camelCase

2023-08-21 06:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<String> deleteProductFromCartWithCartId(@PathVariable Long cart_id) {
przydalby sie tez productId

2023-08-21 06:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<String> addProductToCartWithCartId(@PathVariable Long cart_id) {
przydalby sie productId

2023-08-21 08:44 UTC, enmebaraggesi commented
Poprawiono nazewnictwo, dodano ProductId + rozbudowano o zwracane obiekty

2023-08-21 18:07 UTC, piotr-grosicki requested changes

2023-08-21 18:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<Product> products;
dto nie moze zawierac w sobie innych encji, powinno zawierac ich id lub dto

2023-08-21 18:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private List<Product> products;
tutaj tez

2023-08-21 18:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private User user;
tutaj tez

2023-08-21 18:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
tutaj tez

2023-08-22 05:19 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<Product> products;
ok, przy User wybrałem id, ponieważ koszyk będzie odnosił się do jednego podmiotu

2023-08-22 05:20 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private List<Product> products;
poprawiono

2023-08-22 05:20 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private User user;
poprawiono

2023-08-22 05:20 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
poprawiono

2023-08-22 05:22 UTC, enmebaraggesi commented
Poprawiono w oparciu o istniejącą w obecnym mainie klasę User

2023-08-22 19:06 UTC, merged