JDP230901-18 add GroupRepositoryTestSuite & Setter in Group Class
piotr-grosicki/project-jdp-2309-01 pull request #22
Opened 2023-08-31 13:57 UTC by wojmys

Dodano testy operacji CRUD dla encji. 
Zaktualizowano klasę Group o setter potrzebny na potrzeby testu.

2023-08-31 22:14 UTC, Patryk241194 requested changes
Hej @wojmys 

Popraw w klasie testowej formatowanie.

Co do samego kodu - komentarze poniżej, potrzebne jest kilka poprawek. Warto dodać również test relacji 1:N.

2023-08-31 22:14 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    ProductRepository productRepository;
Stworzyłeś productRepository, ale go nie używasz - musisz zapisać do niego produkty, które tworzysz builderem, a następnie w testach za pomocą repozytorium encji Grupy poprzez metodę getProducts je dodajesz - zerknij sobie na moduł 17 relacje na przykład :)

2023-08-31 22:14 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertEquals("Cars",nameBeforeUpdate);
Robisz testy nie tego co trzeba, test powinien porównywać stan obiektu pobranego z bazy danych po aktualizacji.

2023-09-01 08:52 UTC, wojmys commented
Zmodyfikowano projekt wg uwag.

+dodano @Override dla metod equals i hashCode
+dodano Builder.Default w klasie Group

2023-09-01 19:28 UTC, enmebaraggesi approved these changes
Wojtku, klepię temat, bo testy wydają się oki i przechodzą 👍 napisałem parę komentarzy odnośnie kosmetycznych spraw i jednego optionala bez typu, to jeśli chcesz, popraw sobie i zacommituj, żeby wpadło albo ja, czy tam ktoś inny naniesie te drobnostki później :)

2023-09-01 19:28 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    private Product product3;
product3, 4 i 5 oraz group2 bym wrzucił jako zmienne do metody testowej, gdzie są używane. Bo wykorzystujemy je tylko raz, to nie muszą być deklarowane jako pole :P

2023-09-01 19:28 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        Optional groupById = groupRepository.findById(group.getId());
Zgubił się typ opakowany optionalem :D

2023-09-01 19:28 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertTrue(groups.size() > 0);
można śmiało zastosować `!group.isEmpty()`

2023-09-04 06:42 UTC, wojmys commented
Zastosowałem się do powyższych uwag ;-)

2023-09-04 19:35 UTC, Patryk241194 requested changes
Hej @wojmys,

Mam jeszcze kilka uwag - info w komentarzach.

2023-09-04 19:35 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.deleteById(product2.getId());
W wyniku poprawy metody **setUp()** z komentarza powyżej, teraz usunięcie grupy powoduje również usunięcie produktów. Wynika to z konfiguracji relacji między encjami Group i Product, a dokładnie **CascadeType.ALL**. Zatem wskazane jest usunięcie linijek 81-82, ponieważ produkty już nie istnieją i krzaczy się test.

2023-09-04 19:35 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertNotEquals(groupBeforeUpdate, groupAfterUpdate);
Test nie porównuje zawartości obiektów, ale porównuje same obiekty, czyli groupBeforeUpdate i groupAfterUpdate, które są obiektami Optional<Group>. To oznacza, że test porównuje referencje do tych obiektów, a nie ich stan. Wydaje mi się, że poprawniejsze byłoby na przykład:

    assertEquals("Cars", groupBeforeUpdate.get().getName());
    assertEquals("Toys", groupAfterUpdate.get().getName());
    
Możliwe, że to jeden pies, ale jak zmieniamy nazwę, to konsekwentnie sprawdzałbym czy zmieniła się nazwa.

2023-09-04 19:35 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.deleteById(product2.getId());
Ten sam przypadek co powyżej.

2023-09-04 19:35 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.deleteById(product2.getId());
Ten sam przypadek co powyżej.

2023-09-04 19:35 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteById(group2.getId());
Nie ma potrzeby usuwania produktów, ponieważ usunięcie grupy za nas to zrobi dzięki **CascadeType.ALL** w relacji. Żeby być konsekwentnym to w tym teście powinieneś również dodać:
`groupRepository.deleteById(group1.getId());`

2023-09-05 05:57 UTC, wojmys commented
Update

2023-09-05 07:15 UTC, Patryk241194 approved these changes

2023-09-05 07:16 UTC, merged