JDP230901-17 poprawione/na nowo
piotr-grosicki/project-jdp-2309-01 pull request #24
Opened 2023-09-03 19:26 UTC by enmebaraggesi

W poprzednim pull requeście dodały się jakieś ćmoje boje, poprawiona wersja stoi na nowo - tym razem nie ruszam plików, których nie potrzebowałem do wykonania testów. Zmienicie je sami.

2023-09-03 20:41 UTC, Patryk241194 requested changes
Hej @enmebaraggesi,

Mam jedną uwagę - sprawdź komentarze poniżej, w przypadku działającej/wypełnionej już bazy danych testy mogą nie przejść. 

Stwórz niezależne testy, które nie zależą od rzeczywistej bazy danych produkcyjnej.

2023-09-03 20:41 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        Product product1 = productList.get(0);
Nie do końca się z tym zgadzam - jeśli będziesz robił test na istniejącym DB to Ci to nie przejdzie.

2023-09-03 20:41 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        Product product1 = productRepository.findAll().get(0);
Ta sama sytuacja co wyżej - do poprawy get(0).

2023-09-03 20:41 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertEquals(2, foundList.size());
To też nie przejdzie w sytuacji jeśli bazy danych już istnieją i są zapełnione - podobnie jak assercje poniżej.

2023-09-04 07:45 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        Product product1 = productList.get(0);
Sądzę, że testy na żywej bazie danych to niepoprawne podejście do testowania (nie powinny pozostawiać po sobie śladu), więc w teorii nie powinno się takie coś wydarzyć. Ale jeśli komuś by się chciało tak robić, to lepiej przyjąć, że kod jest uniwersalny, więc poprawiłem.

2023-09-04 07:56 UTC, Patryk241194 approved these changes
Drobna uwaga kosmetyczna w komentarzu. Reszta jest ok. Leci approval.

2023-09-04 07:56 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    List<Product> findAllById(Long id);
**Product findById(Long id)** byłoby poprawniejsze, niemniej jednak twoje też zadziała, więc wrzucam approval. Ale dla kosmetyki można by się doczepić 😇

2023-09-05 07:17 UTC, wojmys approved these changes

2023-09-05 18:48 UTC, merged