JDP230901-20
piotr-grosicki/project-jdp-2309-01 pull request #25
Opened 2023-09-05 21:07 UTC by TomaszGajewski09

2023-09-06 19:01 UTC, enmebaraggesi requested changes
Hejka Tomaszu. Pozostawiam w komentarzach zalecane zmiany. Myślę, że drobne tyrpnięcie klawiaturą i załatwione będzie 😄

2023-09-06 19:01 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +        assertTrue(testUser.getOrders().contains(order2));
Jak test powyżej

2023-09-07 17:29 UTC, TomaszGajewski09 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    @Transactional
Zapomniałem usunąć :D

2023-09-10 06:22 UTC, enmebaraggesi approved these changes
Jest oki, tylko w międzyczasie w main branch się pozmieniły nieco miejsca niektórych klas, więc importy trzeba będzie zastosować w zgodzie z nowymi ich adresami. Plus zmieniło się z Date na samo LocalDate jeśli chodzi o created w Cart :P Być może git każe Ci rozpatrzyć konflikty, jeśli przejdzie testy pomyślnie

2023-09-10 19:45 UTC, Patryk241194 approved these changes

2023-09-10 19:45 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    }
Unikałbym używania `deleteAll();` do kasowania danych. W przypadku większej ilości użytkowników, a błędnie napisanego kodu, może się jednak okazać, że coś jednak zostaje w bazie, albo coś się kasuje podwójnie i wtedy test wyrzuca Ci błąd, a przy użyciu `deleteAll();` kasuje się po prostu cała lista i nie analizujesz ciągu zdarzeń.

2023-09-10 19:45 UTC, Patryk241194 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    @Transactional
celowo użyty @transactional aby ominąć błąd z **lazy loading** - nie będę się czepiał :)

2023-09-10 20:43 UTC, merged