Jdp230901 22 GroupController implemented
piotr-grosicki/project-jdp-2309-01 pull request #26
Opened 2023-09-06 13:49 UTC by wojmys

Dodano rzeczywistą implementację metod w kontrolerze Group.

Utworzono serwis DB oraz mapper.
Przetestowana za pomocą POSTMAN.

2023-09-07 09:32 UTC, enmebaraggesi requested changes
Wojtku siema, zostawiłem Ci parę komentarzy, z czego większość opatrzyłem dopiskiem "KOSMETYKA/PRAKTYKA", co oznacza, że nie jest nam to do szczęścia potrzebne, żeby appka spełniała sztywne normy. Możesz je olać, jak dla mnie na ten moment. Pozostałe rzeczy prosiłbym Cię o poprawienie, żeby nam wszystkim było łatwiej się zgrać z projektem :)

2023-09-07 09:32 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupDto.setId(updatedGroup.getId());
Ja wiem, że tak szybciej 😞 ale obiekty dto powinny pozostawać niezmienne. Dlatego lepiej zastosować mapping z dto do modelu, potem w modelu podmienić id, wrzucić do db, przemapować na dto, zwrócić klientowi.

2023-09-07 09:32 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +@Builder
sio 😝 mamy konstruktor do tworzenia dto. Builder niepotrzebny. Dto to data chunk i jego oczekiwana zawartość pojawia się np. w swaggerze, więc jeśli chcemy przesłać mniej danych niż główny dto zakłada, to tworzymy inny dto 😉 W encji builder potrzebny jest do pominięcia klepania kodu customowych konstruktorów, żeby nie podawać jakichś rzeczy typu null null null za jakieś pola, których na razie nie mamy. No i żeby nie podawać id. W dto podajemy wszystko, co dto powinno pobierać z encji/od klienta.
Ale Setter to na pewno musi zniknąć bo łamie konwencję.

2023-09-07 09:32 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +        return groupRepository.findById(groupId).orElseThrow(GroupNotFoundException::new);
KOSMETYKA/PRAKTYKA: O tutaj 😋 to jest jawne wyrzucenie błędu, a więc "obsługa". Wówczas niepotrzebnym jest `throws` obok deklaracji (które sugeruje niejawne obsłużenie). Usunąłbym throws, zostawił obsługę jawną, bo to jest pożądany scenariusz

2023-09-07 09:32 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +        if (!groupRepository.existsById(groupId)) {
KOSMETYKA/PRAKTYKA: O i tutaj. Porządnie obsługujesz poprzez kontrolę wyrzucanego błędu, więc throws nie jest potrzebne. Throw - jawna praktyka, throws - niejawna, kiedy nie obsługujemy w danym miejscu

2023-09-07 09:50 UTC, wojmys commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    private static final Logger logger = LoggerFactory.getLogger(GroupController.class);
Spoko. Bardzo fajna opcja ;-)

2023-09-07 09:52 UTC, wojmys commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        logger.info("successfully saved");
Spoko. Logi w tym przypadku są tylko opcjonalne. Mogę je usunąć, gdy wszystkie kontrolery będą gotowe, a aplikacja gotowa do odbioru. 
Chodziło mi o dodatkowe potwierdzenie, że motody VOID działają poprawnie.

2023-09-07 13:24 UTC, wojmys commented
Zaktualizowano stosując się do w/w zaleceń.

2023-09-07 19:40 UTC, enmebaraggesi approved these changes

2023-09-09 12:51 UTC, Patryk241194 approved these changes
Hej @wojmys,

Drobne sugestie ode mnie w komentarzach. Controller działa więc leci approval.

2023-09-09 12:51 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        return ResponseEntity.ok(groupAfterUpdate);
To działa z setterami, ale po to masz ten Mapper aby właśnie sczytał @RequestBody groupDto i zmapował go na group. W przyszłości jakby ktoś zdecydował by edytować atrybuty encji to już nie musi wracać i edytować jednocześnie controllerów (**OCP**).

2023-09-09 12:51 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<ProductDto> listOfProducts;
Tutaj to co omawialiśmy na spotkaniu - powinniśmy unikać relacji przesyłania Dto w innych Dto. Warto to przekształcić na przesyłanie id, a potem ewentualnie za pomocą innych mapperów w razie konieczności pobierać informacje produktow z DB poprzez id.

2023-09-09 12:51 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +        return groupRepository.findById(groupId).orElseThrow(GroupNotFoundException::new);
Akurat przy obecnej implementacji `GroupNotFoundException` (wyjątek kontrolowany) musi mieć deklaracje w sygnaturze metody za pomocą klauzuli throws lub obsługi try-catch.

2023-09-09 12:51 UTC, Patryk241194 commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +        if (!groupRepository.existsById(groupId)) {
Nie zgodzę się do końca. Zarówno throw, jak i throws są jawne. Różnica polega na tym, że throw dotyczy rzucania wyjątków, a throws dotyczy deklarowania, które wyjątki mogą być rzucone przez daną metodę. W przypadku powyżej jeśli `GroupNotFoundException` nie dziedziczy RuntimeException lub jej podklas to musimy użyć throws lub obsługę try-catch.

2023-09-09 13:02 UTC, merged

2023-09-09 13:06 UTC, wojmys commented
Spoko. Podszlifuje jeszcze.