Task JDP230901-16 OrderRepositoryTestSuite
piotr-grosicki/project-jdp-2309-01 pull request #27
Opened 2023-09-06 15:41 UTC by CzaHa02

2023-09-06 20:22 UTC, enmebaraggesi requested changes
Hejka. Zostawiam parę komentarzy do requesta. Prosiłbym o naniesienie poprawek. Nad czym bym się zastanowił to - testy nie powinny pozostawiać nic po sobie, o ile H2 sama spuszcza po sobie wodę, tak w przyszłości "potencjalny programista" mógłby dokonać zmian. Dlatego polecam dorobić sprzątanie bazy danych po testach :)

2023-09-06 20:22 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/OrderRepositoryTestSuite.java
> +
Wypadałoby jeszcze dodać powiązanie `product` z `order`

2023-09-06 20:22 UTC, enmebaraggesi commented on src/test/java/com/kodilla/ecommercee/repository/OrderRepositoryTestSuite.java
> +        Assertions.assertTrue(order1.getProducts().contains(product2));
Testujemy dany pobierane z bazy danych. Sugerowałbym w asercjach sprawdzać dane pobierane za pomocą repozytoriów :)

2023-09-06 20:36 UTC, enmebaraggesi commented
Oto błędy z circleci:

OrderRepositoryTestSuite > shouldDeleteOrder() FAILED
    org.springframework.dao.EmptyResultDataAccessException at OrderRepositoryTestSuite.java:101
    
nie przechodzi, bo masz w linijce 101 usuwanie tego obiektu przez Id, który już się usunął razem z Order. Spróbuj przejść do klasy Order i nad polem `products` jest `cascade = CascadeType.ALL`. Zobacz, czy przejdzie, kiedy zmienisz na `cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}`.

ProductRepositoryTestSuite > shouldUpdateData() FAILED
    org.opentest4j.AssertionFailedError at ProductRepositoryTestSuite.java:88

Upewnij się czy masz aktualny kod względem origin/main, bo ProductRepository przechodził poprawnie testy

2023-09-11 15:50 UTC, enmebaraggesi approved these changes

2023-09-11 15:53 UTC, wojmys approved these changes

2023-09-11 15:58 UTC, merged