JDP230901-24 OrderController
piotr-grosicki/project-jdp-2309-01 pull request #30
Opened 2023-09-10 20:47 UTC by TomaszGajewski09

2023-09-11 16:00 UTC, CzaHa02 approved these changes

2023-09-11 17:33 UTC, enmebaraggesi requested changes
Panie Tomku, jest sytuacja taka:
`addProductToOrder`oraz
`deleteProductFromOrder` nie dokonują poprawnie zmian... W sumie to przez chwilę się zastanawiałem co u diaska.
Otóż -> faktycznie w encji `Product` do listy `orders` jest przypisana relacja "rodzicielska" encji. Wystarczy podmienić zarówno w `Order` (przy produktach nazwać odpowiedni joinTable, itp. tak jak obecnie jest w encji Product), jak i w `Product` (przy liście orders ustawić tak samo jak jest przy liście carts).

Poza tym to jak dla mnie elegancko :D

2023-09-11 17:33 UTC, enmebaraggesi commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        Order order = this.getOrderById(productId);
Tutaj się zamieniły miejscami `productId `oraz `orderId`

2023-09-12 08:15 UTC, enmebaraggesi approved these changes

2023-09-12 08:15 UTC, merged